[package]
name = "hello_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"

[workspace]

members = [ "control_flow", "data_type", "error_handle", "http_ie", "lifecycle", "ownership","scrape_url",]
